### ISSUE TITLE
Enable connection via Tor

### ISSUE THREAD

**Issue by weex** [ReinProject/python-rein#1]
Make it possible to run python-rein over Tor by connecting through a running Tor browser. Basically, when run with a --tor switch, I expect that any requests that are not properly directed through Tor would fail. 

Ideally the Tor configuration to happen in one place in the code: rein/lib/config.py

**Comment by bitspill** [comment]
https://github.com/ReinProject/python-rein/pull/50

**Comment by weex** [comment]
True, that closes it.
