### ISSUE TITLE
Undocumented dependence on setuptools package

### ISSUE THREAD

**Issue by mtlynch** [ReinProject/python-rein#115]
I followed [the setup instructions](https://github.com/ReinProject/python-rein/blob/master/doc/HOWTO-setup-rein.md) (except using git instead of a zip) but the setup failed because there's a dependency on `setuptools` which is not mentioned in the instructions:

```shell
$ git clone https://github.com/ReinProject/python-rein.git
$ cd python-rein/
$ git checkout v0.3.1-beta
$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import find_packages, setup
ImportError: No module named setuptools
```

The fix is to add this to the instructions:

```shell
sudo pip install setuptools
```

Tested on Ubuntu 16.04

**Comment by weex** [comment]
Thanks. Fixed also with bce4df96ce6304a32ec0cf4461674cd573f1bd96
