### ISSUE TITLE
In /setup, confirm backup seed, ignore leading/trailing whitespace

### ISSUE THREAD

**Issue by sgornick** [ReinProject/python-rein#125]
When confirming the backup seed, any leading or trailing whitespace will result in the error: "Some of the words are incorrect. Please try again or restart setup."    

There is no valid case where leading or trailing whitespace would be used, so trimming the variable before testing for equivalency would help the user who leaves a leading and/or trailing space on the word.

This occurred with me because I was doing a copy / paste of the 12 word string.

**Comment by weex** [comment]
Thanks @sgornick. Thought I had tested that with all of the copy pasting that I've done to test the setup form but apparently not, anyway was an easy fix which is always great.
