### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by navxio** [ReinProject/python-rein#132]
Installed it with python setup.py install

**Comment by weex** [comment]
There's no uninstaller but it's a pretty basic installation. Application data like documents and user info is stored in `~/.rein`.

The other stuff would be installed wherever Python installs packages to your system. I install it in a virtual environment so the next step would be getting rid of rein-* in `<virtual env>/lib/python2.7/site-packages/`. 

On Ubuntu or OS X without a virtual env it would be in `/usr/local/lib/python2.7/site-packages`. 

Finally delete the folder where the git repo was cloned.
