### ISSUE TITLE
Buyer needs help

### ISSUE THREAD

**Issue by Flamcake** [ReinProject/python-rein#28]
The pre-requisites are way over my head.  Can I hire someone help walk me through set up so I can hire someone on reinproject to create a wordpress blog theme for me?  I then want to have that freelancer answer some questions on their experience for a guest blog post.  Is there a video that walks people through set up on a windows PC?  I have basically zero experience, with linux, command prompts, ubuntu etc.  Thanks!

All I want to do is hire people.  Obviosly I don't provide any value as a freelancer :)

**Comment by weex** [comment]
I'm a bit busy today but if nobody steps up, I can help mid-week. @bitspill @achow101 any time/interest in helping Flamcake get setup?

**Comment by Flamcake** [comment]
Its a paid gig if we have a reasonable price!

**Comment by achow101** [comment]
Sure, I can help here. @Flamcake What is your email? What is your budget?

**Comment by Flamcake** [comment]
great!  karl.nyberg22@gmail.com .  I was hoping to base the price on a few other elance projects I have done.  We can discuss over email if thats ok.  Thanks!

**Comment by weex** [comment]
Closing this since it's more of a forum thread than bug. Thanks.
