### ISSUE TITLE
Failed setup prevents future attempts

### ISSUE THREAD

**Issue by bitspill** [ReinProject/python-rein#32]
I just ran through a `rein setup` however I got the error `Signature verification failed. Please try again.` No problem, probably copy-pasted wrong.

Problem comes in when running `rein setup` again, `Identity already setup.`

**Comment by weex** [comment]
This may be fixed by the bug/32 branch but needs testing.

**Comment by Stemby** [comment]
Also, default should be [enrollment.txt.sig] instead of [enrollment.txt], right?

**Comment by weex** [comment]
Yes, that's correct. I changed it to the same file to simplify the opening, copying, pasting.

**Comment by weex** [comment]
Sorry, I read that wrong. I think just txt is better for simplicity. The Readme needs updating.

**Comment by Stemby** [comment]
Ah, OK, understood.

**Comment by weex** [comment]
Fixed with 53e57db4
