### ISSUE TITLE
Implementing a tagging system

### ISSUE THREAD

**Issue by Stemby** [ReinProject/python-rein#39]
In my opinion a tagging system should be implemented, for general tags ([python], [logo design], etc.) and specific/special tags (e.g. geotags).

Thanks!

**Comment by weex** [comment]
Is this to replace category or do we want a general purpose Tags field that would be filled in with these? I'd be interested to see an example job post document with the various cases of tagging included.

**Comment by Stemby** [comment]
I find categories quite restrictive and probably useless; [Freelancer](https://www.freelancer.com/jobs/) seems to use tags only; [XBTFreelancer](https://www.xbtfreelancer.com/projects) uses both categories and tags ("Type of Work" and "Skills"), but I can't understand the usefulness of the former.

An example could be searching for `[italian] AND [english]` in order to narrow to en→it or it→en translation jobs.

[EDIT]
I found a possible use of categories: separate `[samba] (Software)` from `[samba] (Dance)`.
[/EDIT]

**Comment by weex** [comment]
I like simple tags more than categories. We could change Category to Tags and validate it for letters and spaces only in that field.
