### ISSUE TITLE
Generate private keys automatically.

### ISSUE THREAD

**Issue by weex** [ReinProject/python-rein#45]
We want to make setting up an account easier and address generation is one of the trickier parts.

The client should create a bip39 mnemonic and use that to generate the master address on one branch of a bip32 tree and delegate addresses on another branch. Then the info for just the delegate address branch can be stored in the db. The mnemonic would not be saved but would be displayed with warnings and require typing back in to verify that it was secured by the user.

This would enable the client to automatically generate enrollment updates with new delegate addresses (improving privacy) to be signed offline by the master key on another computer.

**Comment by weex** [comment]
Adding an email exchange to discuss further in this thread.
—————————————————————
Hey Alexander,

Great to hear. I am still trying to flesh out how that private key generation can work from a user perspective given how bip32 HD wallets can be structured.

Rein uses a master/delegate key scheme to provide revocation on the daily (delegate) key should it be compromised. Do you have an opinion on how revocation can work under an HD wallet scenario?

David 
—————————————————————
Hi David,

Now, just to make sure I understood well how wallets work in Rein. We have a master BTC address. This is the basis for account activities and is NOT used for transactions.

Then, we’ve got a delegate public key and a delegate private key. Using the delegate address, we generate new addresses for each transaction. Should the delegate private key be compromised, it’s to be changed as BTC can be stolen.

I see one way of generating private keys automatically, but it’s a security trade-off as we should generate them on one machine with delegate addresses.

Rein generates a recovery mnemonic for the master address. The client authenticates to Rein with the master key passphrase, so he decrypts the account. Recovery is done using the mnemonic. I imagine it mostly as at Blockchain.info, you might wanna check it out. 

Then, Rein generates delegate data. It is revoked when the client recovers his account. Means, we use the delegate data for day-to-day transactions and we don’t compromise the master key.

——

I’m not sure I was very clear now because I’m still studying Bitcoin features, so feel free to ask questions.

Yours,
Alex.
—————————————————————
Hey Alex, Continued responses below.

We can split this into two parts.

1) Upgrading the initial setup to generate a mnemonic, a corresponding master address as the first account in an HD wallet. Then use that to sign the enrollment.

2) Extending the process so a branch of the HD wallet can create a delegate address and figure out how revocation can work with an HD wallet branch while protecting the master branch and hash of the mnemonic seed.

>  Now, just to make sure I understood well how wallets work in Rein. We have a master BTC address. This is the basis for account activities and is NOT used for transactions.
> 
>  Then, we’ve got a delegate public key and a delegate private key. Using the delegate address, we generate new addresses for each transaction. Should the delegate private key be compromised, it’s to be changed as BTC can be stolen.

In the current model, the delegate key would only be changed if it were to become compromised. That revocation bit isn't code at all but that's how it would work in theory. So though not ideal we don't change the delegate to get a new address for each transaction. If we were to be updating an address, we would sign that new address just with the delegate key. The idea is that the delegate is "hot" (online for convenience) while the master is cold, offline for security.

>  I see one way of generating private keys automatically, but it’s a security trade-off as we should generate them on one machine with delegate addresses.
> 
>  Rein generates a recovery mnemonic for the master address. The client authenticates to Rein with the master key passphrase, so he decrypts the account. Recovery is done using the mnemonic. I imagine it mostly as at Blockchain.info, you might wanna check it out. 

I'm familiar with Blockchain.info and client-side encrypted stuff but prefer this master address be kept more secure than that so that long-term identity and reputation building are possible. For this reason, the most I would do is have the seed generated by the client during setup and be used to sign the initial enrollment. After that, it should only exist on paper or be kept offline by the user. To ensure that they do have a copy of it, we would require that they type it back in and compare to what we have in temporary memory (flask session).

-David

**Comment by weex** [comment]
Focusing on 1) above. What I'd like to do first is generate the seed and use m/0 as the master key. Then make m/k'/0 as the first delegate key. Then should we implement more wallet features we could use m/k'/1 for change addresses..just so we have some kind of plan for the long-term. These can be played with in interactive form at https://bit32.org. Thoughts?

**Comment by alexanderdushkin** [comment]
It complies with what we want in the first place - have two branches, cold - master and hot - delegate, so I think it's going to work out.

**Comment by alexanderdushkin** [comment]
PR has been created, check it out.

**Comment by weex** [comment]
Linking https://github.com/ReinProject/python-rein/pull/80

**Comment by weex** [comment]
This is being integrated now for the v0.3 release. Closing the issue as it's basically done.
