### ISSUE TITLE
Attribute Error"

### ISSUE THREAD

**Issue by EssenceOfChaos** [ReinProject/python-rein#51]
During the last step of the setup I'm getting this attribute error when trying to connect with the server. I attempted to sync and receive the same error:

AttributeError: 'NoneType' object has no attribute 'dkey'

I'm stuck there.. what should i do?

**Comment by weex** [comment]
Can you say what OS you're on? What procedure did you follow to do the install? Did you use a virtualenv? Finally, if you try `sqlite3 ~/.rein/local.db` and inside there `select count(1) from identity;` what is the result?

**Comment by EssenceOfChaos** [comment]
I am using the El Capitan OS and I followed the procedure found at
reinproject.org. Everything worked fine until the last step with the
servers.

On Fri, May 20, 2016 at 10:59 PM, David Sterry notifications@github.com
wrote:

> Can you say what OS you're on? What procedure did you follow to do the
> install? Did you use a virtualenv? Finally, if you try sqlite3
> ~/.rein/local.db and inside there select count(1) from identity what is
> the result?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ReinProject/python-rein/issues/51#issuecomment-220755020

## 

-FS

**Comment by weex** [comment]
That error means that no user identity has been saved. Can you try the sqlite command? You could also just delete the local.db file if you want to try the user setup part again.

**Comment by weex** [comment]
Closing this. If the issue still persists, please reply.
