### ISSUE TITLE
Rein fails on `rein bid`

### ISSUE THREAD

**Issue by bajsicki** [ReinProject/python-rein#64]
```
$ rein bid
GET http://rein1-sfo.reinproject.org:2016/query?[keys]
GET http://rein2-ams.reinproject.org:2016/query?[keys]
Verifying block times...
  [#################-------------------]   48%GET http://rein1-sfo.reinproject.org:2016/bitcoin?[keys]

Traceback (most recent call last):
  File "/usr/local/bin/rein", line 9, in <module>
    load_entry_point('rein==0.2.0', 'console_scripts', 'rein')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/surgo/Apps/python-rein/rein/cli.py", line 264, in bid
    live_jobs = filter_out_expired(rein, user, urls, jobs)
  File "/home/surgo/Apps/python-rein/rein/lib/validate.py", line 32, in filter_out_expired
    b = Block(block_hash, data['time'], data['height'])
TypeError: 'Response' object has no attribute '__getitem__'

```

Any solutions? Every time I run it, it ends up the same. I'm not a techie, so I can't pretend to know what it means, but it does appear that there's something wrong with the keys/ hashes/ blocks it generated?

Latest Bunsen Linux, 64bit, etc. etc. All's updated, and done according to documentation.

**Comment by bajsicki** [comment]
Two days passed, now it appears to be working okay. Perhaps the servers needed to update?
There's only one job there, which is a bit disappointing.

**Comment by weex** [comment]
Hey Angel418, sorry just saw this. It's possible the one server was still updating and caused an error when bitcoind was down which the client should obviously tolerate. When you say latest was that the latest tagged version or master?

Also, interested to know what kinds of jobs you'd be looking to bid on.

**Comment by bajsicki** [comment]
Yes, latest master. Looking for writing/ consulting work. I write digital copy and hypnosis scripts, as well as offer hypnosis sessions to critical individuals in companies, in order to uphold their productivity through times of crisis.

**Comment by weex** [comment]
Please email me or ping me in #Rein on freenode to brainstorm on writing.
