### ISSUE TITLE
How to recover a lost Rein account?

### ISSUE THREAD

**Issue by alexanderdushkin** [ReinProject/python-rein#76]
Let's pretend a user loses his local Rein copy together with the .rein folder. When this user enrolls again with the same BTC addresses and keys, does Rein just create a duplicate on the server as I think or it recovers the old account?

**Comment by weex** [comment]
Access to each server is authenticated where necessary with the delegate key so as long as they have that, they're good to go. They shouldn't enroll again if they still have the master privkey. Instead they can import a json file from command line to recreate the identity record.

**Comment by alexanderdushkin** [comment]
Yeah, I just wanted to make sure importing accounts still makes sense in context of automatic BIP32/39 data generation. If the server created duplicates, then it would've made no sense to import an account as you could create another one with the same outcome.

**Comment by weex** [comment]
You could upload multiple enrollments to the server and in theory only the newest one for a master privkey should count. We'd need to include a time in the enrollment though so that's a later thing.
