### ISSUE TITLE
Streamline web form feedback

### ISSUE THREAD

**Issue by chbeltz** [ReinProject/python-rein#81]
Currently, forms (such as the one located at "/post") specifically use "render_error(form.FIELD_NAME)" to allow for displaying errors right below the affected field. At the same time, errors seem to be mostly displayed via Flask's "flash" functionality. 

Deciding for one of those two possibilities and providing an example showing how a form should be set up to properly display errors would probably improve both future developers' and users' experience.

**Comment by alexanderdushkin** [comment]
I would actually prefer JavaScript for that. It will simplify the code a lot. Take a look at what I've done with BIP32/39 registration.

**Comment by weex** [comment]
In the future, we'd like to be able to create both Chrome extension and client-side encrypted versions of the client so I can see a strong future for javascript. For that reason, I don't think we need to worry too much about optimizing python-rein to this level.
